### ISSUE TITLE
Live Scores

### ISSUE THREAD

**Issue by meGodDev** [felipeall/transfermarkt-api#26]
Is there a way of getting live scores from live matches?

**Comment by felipeall** [comment]
Hello @meGodDev! Actually this kind of live features is not in my scope right now because I want to first focus on collecting historical data for competitions, clubs and players.

I believe it would be possible to implementing a similar scraping strategy to the [https://www.transfermarkt.com/ticker/index/live](https://www.transfermarkt.com/ticker/index/live) page but unfortunatelly I won't be able to work on it in a near future
