### ISSUE TITLE
Retrieving the marketValueHistory is not working any more

### ISSUE THREAD

**Issue by DriesDeprest** [felipeall/transfermarkt-api#38]
Retrieving the marketValueHistory of a player via https://github.com/felipeall/transfermarkt-api/blob/main/app/api/endpoints/players.py#L29 is not be working any more.

It seems that no high charts page exists any more in the HTML response, which is where the code expects the market value history information to live: https://github.com/felipeall/transfermarkt-api/blob/main/app/services/players/market_value.py#L56

**Comment by felipeall** [comment]
Hi @DriesDeprest,

Thank you for pointing this out. It looks like the market value history chart has been modified in the website, so I will deploy a hot-fix in order to make it work again.

Unfortunately I don't think it is possible to extract the club id for each point in the graph anymore (I will take a look on that specific issue later while developing the new API version: https://github.com/felipeall/transfermarkt-api/tree/v2)
