### ISSUE TITLE
Server not working!

### ISSUE THREAD

**Issue by hadisotudeh** [felipeall/transfermarkt-api#52]
Thanks for this great repo.

It seems the API is broken now when I access it via https://transfermarkt-api.vercel.app/competitions/GB1/clubs, see:
![image](https://github.com/felipeall/transfermarkt-api/assets/2101643/606822d1-4ae2-40c1-9f0f-c21434d92e22).

**Comment by felipeall** [comment]
Hey @hadisotudeh ! Thanks for letting me know about it, I believe something crashed in the server side and didn't restarted automatically. I just redeployed the application and it should be fine, please let me know if you find any other issue!

**Comment by hadisotudeh** [comment]
Great, it works now. Thanks for the quick response. I think you can close this issue.

**Comment by hadisotudeh** [comment]
Just to let you know that the server is down again!

**Comment by felipeall** [comment]
hey @hadisotudeh , thanks for the heads up! Sometimes the server may crash when it receives a lot of concurrent requests (because it is currently hosted in a free service just for testing purposes). So if one wants to integrate it in an application, it is advised to deploy it in a private cloud environment. Thanks!
